### ISSUE TITLE
The value of exec_dir ini option can't change with php_admin_value

### ISSUE THREAD

**Issue by Joungkyun** [OOPS-ORG-PHP/mod_execdir#10]
In apache virtual host, can't change value of the exec_dir option with php_admin_value directive.

```apache
<VirtualHost *:80>
    ServerName domain.com
    blah blah~~~~

    php_admin_value exec_dir /var/lib/php/domain.com/bin
</VirtualHost>
```

Current, the value of exec_dir option only can be changed with php ini configuration.

**Comment by Joungkyun** [comment]
Current, the type of exec_dir is ZEND_INI_SYSTEM.

I think that change type to ZEND_INI_SYSTEM to PHP_INI_SYSTEM, can enable to change with php_admin_value.

```diff
 /* {{{ ini_entries[]
  */
 PHP_INI_BEGIN ()
-    STD_PHP_INI_ENTRY ("exec_dir", PHP_EXECDIR, ZEND_INI_SYSTEM, OnUpdateString, exec_dir, zend_execdir_globals, execdir_globals)
+    STD_PHP_INI_ENTRY ("exec_dir", PHP_EXECDIR, PHP_INI_SYSTEM, OnUpdateString, exec_dir, zend_execdir_globals, execdir_globals)
 PHP_INI_END ()
 /* }}} */
```

**Comment by yoonjoongkang** [comment]
1) php-fpm이 아닌 아파치 모듈로 테스트 하였습니다.
```apache
LoadModule php5_module        modules/libphp5.so
```
2) php_admin_flag 가 아닌 php_admin_value로 테스트 하였습니다.
```apache
<VirtualHost *:80>
     ServerName test2.com
     php_admin_value exec_dir /home/test2/bin/
</VirtualHost>
```
3) php 소스 코드는 아래와 같습니다.
```php
echo exec('DEBUG:ls -al');
echo ini_get('safe_mode_exec_dir');
```
4) 출력결과
```
-- make_cmdargv ------
Origianl : DEBUG:ls
cmd      : ls (2)
argv     :  -al (4)
----------------------
Orig Cmd ==> ls -al
Conv Cmd ==> /var/lib/php/bin/ls -al
--
/home/test2/bin/
```
5) Debug 경로 : /var/lib/php/bin/
    ini_get 경로 : /home/test2/bin/ 

6) 아직도 ini_get 경로를 따르지 않는것 같습니다.

**Comment by Joungkyun** [comment]
환경을 만들어서 다시 확인해 보겠습니다. issue reopen 합니다. 1.0.1 release 는 이 issue 해결 후에 하도록 하겠습니다.

**Comment by Joungkyun** [comment]
본문의 ***php_admin_flag*** 는 오타 입니다. 실제 테스트는 ***php_admin_value*** 로 했습니다. (현재 본문에는 ***php_admin_flag*** 를 ***php_admin_value*** 로 수정해 놓았습니다.

그리고, 다음 환경에서는 정상적으로 ***php_admin_value*** 옵션이 정상 동작함을 확인 했습니다.

* case PHP ***7.1.0*** php-fpm
* case PHP ***7.0.14*** php-fpm
* case apache ***2.4*** and PHP ***7.0.14*** apache module (mod_php7.so)
* case PHP ***5.6.29*** php-fpm
* case apache ***2.2*** PHP ***5.3.38*** apache module (mod_php5.so)

***INI configration:***
```
execdir extension support
Summary			jailed system function
URL			http://github.com/OOPS-ORG-PHP/mod_execdir
Build version		1.0.1beta
Default Exec DIR	/var/php/bin

Directive	Local Value	Master Value
exec_dir	/tmp/php/bin	/var/php/bin
```
***Default Exec DIR*** 값은 빌드시의 ***configure*** 의 ***--with-execdir*** 의 옵션 값이며, ***Local Value*** 는 ***php_admin_value*** 에 의해서 설정된 값이고, ***Master Value*** 는 php.ini에 설정된 값입니다.


***Test Configuration:***
```apache
<VirtualHost *>
    DocumentRoot /home/httpd/html
    ServerName an2.pkg.oops.org
    <IfModule mod_php5.c>
        php_admin_value exec_dir /tmp/php/bin
    </IfModule>
</VirtualHost>
```

***Results:***
```
exec_dir           : /tmp/php/bin
safe_mode_exec_dir : /var/lib/php/bin
open_basedir       : /home/httpd/html:/var/lib/php:/usr/share/php/pear
-- make_cmdargv ------
Origianl : DEBUG:ls
cmd      : ls (2)
argv     :  -al (4)
----------------------

Orig Cmd ==> ls -al
Conv Cmd ==> /tmp/php/bin/ls -al
--
```

5.2는 아직 환경 준비가 안되서 못해보기는 했는데, 위의 테스트 내용을 보니 확인이 필요한 사항이 있습니다.

1. mod_execdir 확장 모듈로 테스트를 하셨나요? 아니면 mod_execdir/patches 에 있는 patch를 이용해서 PHP에 static하게 patch를 하셨는지요?

2. 만약 mod_execdir 확정 모듈을 사용했다면, safe_mode_exec_dir 옵션은 사용하지 않고 exec_dir 옵션을 사용합니다. 이 부분 정확하게 확인해 주세요. safe_mode_exec_dir은 php 5.3 이하에서 static 하게 패치를 했을 때 사용합니다. mod_execdir 확장 모듈에서는 버전에 상관 없이 exec_dir 옵션만을 사용 합니다.

P.S.
주의 하실 것은, PHP 5.3 이하에서 ***safe_mode*** 가 ***On*** 이 되어 있으면 동작이 원하는 대로 되지 않습니다. ***safe_mode*** 가 On일 경우, ***safe_mode***의 Parser가 동작하게 되므로 ***safe_mode_exec_dir*** 의 설정 값으로 동작하게 되며, 또한, command parser가 mod_execdir 의 paser가 아닌 ***safe_mode*** 에서 사용하는 파서로 동작을 하게 됩니다. 그러므로 테스트는 꼭 ***safe_mode*** 설정이 ***Off*** 인 상태에서 해야 합니다.

**Comment by Joungkyun** [comment]
***Apache*** 1.3 + ***PHP*** 5.2.17 환경에서도 정상 동작 하는 것을 확인 했습니다.

다음 사항 다시 확인 해 주세요.

1. safe_mode ***Off*** 환경이어야 함.
2. ***mod_execdir*** 확장 모듈로 테스트 한 것인지, 아니면 ***mod_execdir/patches*** 에 있는 patch를 적용해서 PHP를 빌드해서 테스트 한 것인지
3. ***safe_mode_exec_dir*** 설정값과 헷갈린 것이 아닌지.. ***safe_mode_exec_dir*** 설정은 사용하지 않고 ***exec_dir*** 설정을 사용 함

다음은 ***Apache*** 1.3 + ***PHP*** 5.2.17 환경의 설정 값입니다.

***INI entries:***
```
execdir extension support
Summary			jailed system function
URL			http://github.com/OOPS-ORG-PHP/mod_execdir
Build version		1.0.1beta
Default Exec DIR	/vat/tmp/bin

Directive	Local Value	Master Value
exec_dir	/tmp/php/bin	/var/lib/php1/bin
```

***Default Exec DIR*** 값은 빌드시의 ***configure*** 의 ***--with-execdir*** 의 옵션 값이며, ***Local Value*** 는 ***php_admin_value*** 에 의해서 설정된 값이고, ***Master Value*** 는 php.ini에 설정된 값입니다.



***Apache Configuration:***
```apache
<VirtualHost *>
    DocumentRoot /home/httpd/html
    ServerName an1.pkg.oops.org

    <IfModule mod_php5.c>
        php_admin_value exec_dir /tmp/php/bin
    </IfModule>
</VirtualHost>
```

***Test Result:***
```
exec_dir           : /tmp/php/bin
safe_mode_exec_dir : /var/lib/php/bin
open_basedir       : 
-- make_cmdargv ------
Origianl : DEBUG:ls
cmd      : ls (2)
argv     :  -al (4)
----------------------

Orig Cmd ==> ls -al
Conv Cmd ==> /tmp/php/bin/ls -al
--
```

**Comment by yoonjoongkang** [comment]
제가 메뉴얼을 정독하지 못해서 실수로 safe_mode_exec_dir로 적용했네요.
번거럽게 해드려 죄송합니다.
수고 많으셨습니다.
