### ISSUE TITLE
절대 경로 문의 드립니다.

### ISSUE THREAD

**Issue by yoonjoongkang** [OOPS-ORG-PHP/mod_execdir#14]
확장 모듈 유용하게 잘 사용하고 있습니다.
사용중 절대 경로 문제가 발견 되어 문의 드립니다.

서버 설정
```
  <IfModule php5_module>
    php_admin_value exec_dir /home/user/bin
  </IfModule>
```

php 실행
```
echo exec('DEBUG:/testbin/command1');
```

php 실행 결과
```
-- make_cmdargv ------
Origianl : DEBUG:/testbin/command1
cmd      : /testbin/command1 (16)
argv     :  (0)
----------------------

Orig Cmd ==> command1
Conv Cmd ==> /home/user/bin/command1
--
```
exec_dir 경로로 지정한 디렉토리 이하의 서브디렉토리에 있는 command를 실행 하려고 합니다.
디버깅을 해보니 /testbin/ 서브디렉토리명이 삭제된 상태로 명령어가 실행이 됩니다.
Conv Cmd가  /home/user/bin/testbin/command1  로 실행을 할 수 있는 방법은 없을까요?

감사합니다.

**Comment by Joungkyun** [comment]
그렇게 하려는 이유가 뭐죠? 별로 그럴일이 없을 것 같은데요. 혹시 virtual host 별 또는 특정 조건 별로 exec_dir 을 분리하고 싶은 건가요? 그렇다면 apache에서 Directory 등등으로 분리할 수 있을 것 같은데요.

경로를 다 날려 버리는 이유는, 기존의 PHP 코드를 수정하지 않아도 동작하도록 하기 위함이 있습니다.

**Comment by yoonjoongkang** [comment]
여러곳의 결제, 실명인증등을 사용할때 동일한 명령어가 중복되어 사용될 경우가 있었습니다.
그래서 각 업체별로 디렉토리를 나누고 명령어를 실행하려는 것입니다.
물론 명령어를 다른 이름으로 바꾼후 사용할 수 있지만 최대한 명령어명은 바꾸지 않는것이 좋을것 같아 디렉토리별로 세분화 시키려는 것이었습니다.

# 명령어명을 이름없이 그대로 사용
/home/user/bin/company1bin/command1
/home/user/bin/company2bin/command1
/home/user/bin/company1bin/logs
/home/user/bin/company2bin/logs

# 명령어와 관련 로그 디렉토리명 변경
/home/user/bin/company1bin_command1
/home/user/bin/company2bin_command1
/home/user/bin/company1bin_logs
/home/user/bin/company2bin_logs

감사합니다.

**Comment by Joungkyun** [comment]
일단, parser에서 디렉토리를 보존할 기준을 세우는 것이 쉽지 않습니다. 예를 들어 현재 구조에서는 경로가 어떻게 되든 특정 디렉토리에서 찾아서 실행을 하기 때문에, php 코드 수정을 하지 않아도 되는 장점이 있지만, 디렉토리 구조를 보존하는 순간, 이 규칙이 깨어지게 되므로, php 코드 수정이 발생해야 하는 문제가 있습니다. 

그냥 실행 파일 이름을 변경 하는 것을 권고 드립니다.
