### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/execdir.so' - /usr/lib64/php/modules/execdir.so: undefined symbol: zend_hash_str_del in Unknown on line 0

### ISSUE THREAD

**Issue by digirave** [OOPS-ORG-PHP/mod_execdir#19]
No problem with php 7.1.11-1

However when trying to use with php 5.6.32-1
The most recent version shows the following error when running php:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/execdir.so' - /usr/lib64/php/modules/execdir.so: undefined symbol: zend_hash_str_del in Unknown on line 0

**Comment by Joungkyun** [comment]
What is the version of mod_execdir that is built?

The error you are seeing occurs when you load the extension file built in php 7.1 from php 5.6.
Check your build environment. (check main/php_version.h)

for examples:

```
[root@an3 mod_execdir-1.0.2]$ ./configure | grep -- "-I"
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
[root@an3 mod_execdir-1.0.2]$ cat /usr/include/php/main/php_version.h  | grep PHP_VERSION
#define PHP_VERSION "7.0.23"
#define PHP_VERSION_ID 70023
[root@an3 mod_execdir-1.0.2]$
```

**Comment by digirave** [comment]
이 건은 우선 재설치 하니까 되기 때문에, 해결으로 표기해도 될 것 같습니다.
희안한 것은 재설치 전에 아래와 같이 버젼을 확인했는데 이상해 보이지 않네요.
[root@72 mod_execdir]# ./configure | grep -- "-I"
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
[root@72 mod_execdir]# cat /usr/include/php/main/php_version.h  | grep PHP_VERSION
#define PHP_VERSION "5.6.32"
#define PHP_VERSION_ID 50632

재설치나 초기 테스트 설치 자체를 스크립트로 해서 명령어 친 것은 동일한데 왜 문제가 발생했는지 모르겠습니다.
무엇인가 제가 잘못했을 듯한데, 무엇을 잘못했는지는 잘 모르겠습니다.

Install method:
cd /root/php
git clone https://github.com/OOPS-ORG-PHP/mod_execdir/
cd /root/php/mod_execdir
phpize
./configure --with-execdir= --with-php-config=/usr/bin/php-config
make test PHP_EXECUTABLE=/usr/bin/php
make install

**Comment by digirave** [comment]
제가 보기에 기존 파일들이 제거 안된 상태에서 git clone 이 작동해서 그럴 것 같기도 합니다.
재설치할 때 디렉토리를 지우고 시행했습니다.
해당 부분은 설치 과정 미스인 것 같습니다. 번거롭게 해서 죄송합니다.

The above problem seems to a problem with my install script, due to git clone not overwriting prior download.
After deleting install dir and recloning from master, problem has disappeared.
