### ISSUE TITLE
backquote and $() syntax weakness after semi colon

### ISSUE THREAD

**Issue by Joungkyun** [OOPS-ORG-PHP/mod_execdir#8]
If you run a shell command after a semicolon, there is a problem that the backticks or $() syntax is not filtered.

for examples:

```php
<?php
exec('ls -al;$(echo "hi" > /tmp/c.txt)');
exec('ls -al;`echo "hi"  > /tmp/d.txt`');
exec('ls -al;`ps aux     > /tmp/e.txt`');
?>
```

This bug is reported by 강윤중<cgidhtml&commat;naver.com> at https://oops.org/SERVICE/jsboard/read.php?table=jsboard_oopsQnA&no=53500

**Comment by Joungkyun** [comment]
reopen this issue because test this patch and will repatch the patches/*.patch.

**Comment by yoonjoongkang** [comment]
추가적인 || , && 연산문까지 테스트했는데 잘되는것 같습니다.
수고하셨습니다.
